"""Alembic environment — async engine over asyncpg.

The DSN is read from the POSTGRES_DSN environment variable, never from a
committed file (DOC-010 § Security: secrets are never committed to version
control; DOC-013 § Dependency & Composition — configuration is passed in).

Migrations in this repository are HAND-WRITTEN, not autogenerated: Alembic's
autogenerate does not reliably emit native Postgres ENUMs, STORED generated
columns, or GIN indexes, all of which DOC-014 requires. target_metadata
stays None deliberately.
"""

import asyncio
import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# The connection URL comes from the environment, not from alembic.ini.
_dsn = os.environ.get("POSTGRES_DSN")
if _dsn:
    config.set_main_option("sqlalchemy.url", _dsn)

# Hand-written migrations (see module docstring); no autogenerate target.
target_metadata = None


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    Configures the context with just a URL and not an Engine.
    Calls to context.execute() here emit the given string to the script
    output.
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(connection=connection, target_metadata=target_metadata)

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Run migrations in 'online' mode with an async engine (asyncpg)."""
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
