"""blockchain_facts table (DOC-012 § B.1, DOC-014 type mappings).

Hand-written, not autogenerated: Alembic autogenerate does not reliably emit
native Postgres ENUMs, STORED generated columns, or GIN indexes — all
required by DOC-014.

DOC-014 § Migration Policy: blockchain_facts migrations are additive-only.
From this revision onward, no column here is ever altered, renamed, dropped,
or backfilled; and no migration may ever UPDATE a FINALIZED row. The
downgrade deliberately does NOT drop this table (forward-only policy:
append-only data does not disappear by running history backward).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1c7f0a9d401"
down_revision: str | None = "4ec2a3c4a644"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Native Postgres ENUMs — a second, independent line of defense that
    # rejects invalid values at the database layer too (DOC-014 § Standard
    # mappings).
    fact_type_enum = sa.Enum(
        "PAIR_CREATED",
        "SWAP_EXECUTED",
        "LIQUIDITY_ADDED",
        "LIQUIDITY_REMOVED",
        name="fact_type_enum",
        native_enum=True,
    )
    fact_type_enum.create(op.get_bind(), checkfirst=True)

    confirmation_status_enum = sa.Enum(
        "PENDING",
        "CONFIRMED",
        "FINALIZED",
        "ORPHANED",
        name="confirmation_status_enum",
        native_enum=True,
    )
    confirmation_status_enum.create(op.get_bind(), checkfirst=True)

    op.execute(
        """
        CREATE TABLE blockchain_facts (
            -- Natural composite key: chain_id:tx_hash:log_index
            -- (ADR-006 § Idempotency — no surrogate UUID).
            fact_id             TEXT        PRIMARY KEY,
            schema_version      TEXT        NOT NULL,
            chain_id            BIGINT      NOT NULL,
            fact_type           fact_type_enum NOT NULL,
            block_number        BIGINT      NOT NULL,
            block_hash          VARCHAR(66) NOT NULL,
            tx_hash             VARCHAR(66) NOT NULL,
            log_index           BIGINT      NOT NULL,
            -- Triple Timestamp Standard: always TIMESTAMPTZ (DOC-014).
            event_time          TIMESTAMPTZ NOT NULL,
            observed_at         TIMESTAMPTZ NOT NULL,
            ingested_at         TIMESTAMPTZ NOT NULL,
            confirmation_status confirmation_status_enum NOT NULL,
            confirmations       BIGINT      NOT NULL,
            -- Discriminated payload as JSONB (DOC-014 § The Discriminated
            -- Payload); Pydantic validates shape before write.
            payload             JSONB       NOT NULL,
            -- Wallet involvement, STORED generated column (DOC-014 § One
            -- field earns that treatment already). PAIR_CREATED has no
            -- wallet fields → empty array.
            involved_wallets    TEXT[] GENERATED ALWAYS AS (
                CASE fact_type
                    WHEN 'SWAP_EXECUTED'     THEN ARRAY[payload->>'sender', payload->>'recipient']
                    WHEN 'LIQUIDITY_ADDED'   THEN ARRAY[payload->>'provider']
                    WHEN 'LIQUIDITY_REMOVED' THEN ARRAY[payload->>'provider']
                    ELSE ARRAY[]::TEXT[]
                END
            ) STORED,
            CONSTRAINT ck_confirmations_non_negative CHECK (confirmations >= 0)
        )
        """
    )

    # Indexes per DOC-014 § Indexing Strategy — each serves a documented
    # query pattern, nothing general-purpose.
    op.execute(
        "CREATE INDEX ix_blockchain_facts_chain_status "
        "ON blockchain_facts (chain_id, confirmation_status)"
    )
    op.execute(
        "CREATE INDEX ix_blockchain_facts_chain_block "
        "ON blockchain_facts (chain_id, block_number)"
    )
    # GIN for /v1/wallets/{id}/activity membership queries.
    op.execute(
        "CREATE INDEX ix_blockchain_facts_involved_wallets "
        "ON blockchain_facts USING gin (involved_wallets)"
    )


def downgrade() -> None:
    # Forward-only (DOC-014 § Migration Policy): a downgrade that would DROP
    # a table containing blockchain_facts data is not written.
    pass
