"""market_bars hypertable (DOC-012 § B.3, DOC-014 § TimescaleDB Hypertables).

Hand-written, not autogenerated: Alembic autogenerate can't handle
TimescaleDB hypertables, native ENUMs, or compression policies.

DOC-014 § TimescaleDB Hypertables:
- Partitioning: bar_start_time, 7-day chunks
- Compression: compress chunks older than 30 days
- Index: (pair_id, interval, bar_start_time DESC) — primary research query
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4f8a1b2c3e5"
down_revision: str | None = "c3e9d2f5a817"  # after M2's blockchains+checkpoints migration
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Native Postgres ENUM for bar intervals (DOC-014 § Standard mappings).
    bar_interval_enum = sa.Enum(
        "1m", "5m", "15m", "1h",
        name="bar_interval_enum",
        native_enum=True,
    )
    bar_interval_enum.create(op.get_bind(), checkfirst=True)

    op.execute(
        """
        CREATE TABLE market_bars (
            -- Composite PK: bar_id + bar_start_time. TimescaleDB
            -- hypertables require the partitioning column in any unique
            -- index (including PK).
            bar_id              TEXT        NOT NULL,
            schema_version      TEXT        NOT NULL DEFAULT '1.0',
            pair_id             TEXT        NOT NULL,
            chain_id            BIGINT      NOT NULL,
            interval            bar_interval_enum NOT NULL,
            bar_start_time      TIMESTAMPTZ NOT NULL,
            bar_end_time        TIMESTAMPTZ NOT NULL,
            -- OHLCV: NUMERIC (unconstrained precision, DOC-014 § Type
            -- Mapping Rules — Price / Ratio / Derived-USD category).
            open                NUMERIC     NOT NULL,
            high                NUMERIC     NOT NULL,
            low                 NUMERIC     NOT NULL,
            close               NUMERIC     NOT NULL,
            volume_base         NUMERIC     NOT NULL,
            volume_quote        NUMERIC     NOT NULL,
            trade_count         INTEGER     NOT NULL,
            vwap                NUMERIC     NOT NULL,
            buy_volume          NUMERIC     NOT NULL,
            sell_volume         NUMERIC     NOT NULL,
            -- source_fact_range as two columns (DOC-014 § Standard
            -- mappings — tuple stored as two columns).
            source_fact_range_start TEXT    NOT NULL,
            source_fact_range_end   TEXT    NOT NULL,
            is_provisional      BOOLEAN     NOT NULL DEFAULT FALSE,
            computed_at         TIMESTAMPTZ NOT NULL,
            PRIMARY KEY (bar_id, bar_start_time),
            -- CHECK constraints (DOC-014 § Data Integrity Constraints).
            CONSTRAINT ck_volume_base_non_negative CHECK (volume_base >= 0),
            CONSTRAINT ck_volume_quote_non_negative CHECK (volume_quote >= 0),
            CONSTRAINT ck_buy_volume_non_negative CHECK (buy_volume >= 0),
            CONSTRAINT ck_sell_volume_non_negative CHECK (sell_volume >= 0),
            CONSTRAINT ck_trade_count_non_negative CHECK (trade_count >= 0)
        )
        """
    )

    # Convert to TimescaleDB hypertable, partitioned by bar_start_time
    # with 7-day chunks (DOC-014 § TimescaleDB Hypertables).
    op.execute(
        "SELECT create_hypertable('market_bars', 'bar_start_time', "
        "chunk_time_interval => INTERVAL '7 days')"
    )

    # Compression policy: compress chunks older than 30 days (DOC-014).
    op.execute(
        "ALTER TABLE market_bars SET (timescaledb.compress = true)"
    )
    op.execute(
        "SELECT add_compression_policy('market_bars', INTERVAL '30 days')"
    )

    # Primary research query index (DOC-014 § Indexing Strategy).
    op.execute(
        "CREATE INDEX ix_market_bars_pair_interval_time "
        "ON market_bars (pair_id, interval, bar_start_time DESC)"
    )


def downgrade() -> None:
    # Forward-only (DOC-014 § Migration Policy).
    pass
